version: '3.7'

services:

  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "${DRUPAL_IMAGE}"
    volumes:
      - .:/app:delegated
      - ssh:/tmp/druid_ssh-agent:ro
    build:
      context: ./docker/local
    environment:
      APP_ENV: "${APP_ENV:-dev}"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      # XDEBUG_ENABLE: "true"
      # DOCKERHOST: host.docker.internal
      REDIS_HOST: redis
      SOLR_HOST: solr
      SOLR_PORT: 8983
      SOLR_PATH: "/"
      SOLR_CORE: dev
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:6-alpine
    networks:
      - internal
  solr:
    container_name: "${COMPOSE_PROJECT_NAME}-solr"
    build: ./docker/solr
    volumes:
      - solr_data:/var/lib/solr
    ports:
      - 8983
    networks:
      - internal
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/db:mysql5.7-drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  solr_data:
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
