---
vagrant_hostname: julkaisut.test
vagrant_machine_name: julkaisut
vagrant_ip: 192.168.88.12

# Automatically swapped to vboxsf on Windows.
vagrant_synced_folder_default_type: nfs
# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    destination: /var/www/drupalvm
    type: "{{ vagrant_synced_folder_default_type }}"
    mount_options: ['nolock', 'noatime', 'actimeo=1']

# Needs to match with what we have in .env and vagrant_synced_folders.
drupal_core_path: "/var/www/drupalvm/web"
drupal_domain: "{{ vagrant_hostname }}"

# Manage Drupal through composer manually
drupal_build_composer_project: false
drupal_composer_dependencies: []
drupal_install_site: false
configure_drush_aliases: false

installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  # - pimpmylog
  # - redis
  # - ruby
  # - selenium
  - solr
  # - tideways
  # - upload-progress
  # - varnish
  - xdebug
  # - xhprof

php_packages_extra: []

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - vim

composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }

# If you want to adjust this, create a local.config.yml file where you override
# the value. This file is not tracked in git.
vagrant_memory: 1024

# XDebug configuration. Disabled for better performance.
php_xdebug_idekey: VSCODE
php_xdebug_default_enable: 0
php_xdebug_remote_autostart: "true"
