popup_agreed:
  value: '<h3>Thank you for accepting cookies</h3><p>You can now hide this message or find out more about cookies.</p>'
popup_agree_button_message: Accept
popup_info:
  value: '<h3>We use cookies on this site to enhance your user experience</h3><p>By clicking the Accept button, you agree to us doing so.</p>'
mobile_popup_info:
  value: '<h3>We use cookies on this site to enhance your user experience</h3><p>By tapping the Accept button, you agree to us doing so.</p>'
popup_link: '<front>'
disagree_button_label: 'No, thanks'
withdraw_message:
  value: '<h3>We use cookies on this site to enhance your user experience</h3><p>You have given your consent for us to set cookies.</p>'
