_core:
  default_config_hash: ey8bRwK17YbAVEX7GEm09YR5UneOQ_Nqzh6a3V-rIP0
langcode: en
applies_admin_routes: true
include_invalid_paths: false
excluded_paths: ''
replaced_titles: 'Helsinki lehti::Helsinki-lehti'
custom_paths: "/fi/search :: Hakutulokset\r\n/sv/search :: Sökresultat\r\n/en/search :: Search results"
include_home_segment: true
home_segment_title: Etusivu
home_segment_keep: false
include_title_segment: true
title_from_page_when_available: true
title_segment_as_link: true
use_menu_title_as_fallback: true
use_page_title_as_menu_title_fallback: true
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: false
term_hierarchy: false
use_site_title: false
add_structured_data_json_ld: true
capitalizator_mode: none
capitalizator_ignored_words: {  }
capitalizator_forced_words: {  }
capitalizator_forced_words_case_sensitivity: true
capitalizator_forced_words_first_letter: false
follow_redirects: true
