mode: process_untranslated
_core:
  default_config_hash: NlDIUdPDDX0V4owUbxlYWoCwMZv_Wnv-wqzepvT5drs
langcode: fi
untranslated_handler: no_link
hide_current_language: false
hide_single_link: false
show_langcode: false
