_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: fi
hotlink: false
origin: 'https://julkaisut.hel.fi'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
